/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FruitDataRouteImport } from './routes/fruitData'
import { Route as IndexRouteImport } from './routes/index'

const FruitDataRoute = FruitDataRouteImport.update({
  id: '/fruitData',
  path: '/fruitData',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fruitData': typeof FruitDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fruitData': typeof FruitDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fruitData': typeof FruitDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fruitData'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fruitData'
  id: '__root__' | '/' | '/fruitData'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FruitDataRoute: typeof FruitDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/fruitData': {
      id: '/fruitData'
      path: '/fruitData'
      fullPath: '/fruitData'
      preLoaderRoute: typeof FruitDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FruitDataRoute: FruitDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
